name: "Auto Update"
on:
  workflow_dispatch:
  schedule:
    - cron: "* 1 * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get IP
        run: |
          echo Get IP
          curl -s https://raw.githubusercontent.com/ymyuuu/IPDB/main/proxy.txt -o ${GITHUB_WORKSPACE}/proxy.txt

      - name: GEO
        run: |
          if [ -f ${GITHUB_WORKSPACE}/addressesapi.txt ];then
            rm -f ${GITHUB_WORKSPACE}/addressesapi.txt
          fi
          for ip in $(cat ${GITHUB_WORKSPACE}/proxy.txt)
          do
            local=$(curl -sL http://ip-api.com/json/${ip} | jq -r .countryCode)
            echo ${ip}#${local}
            echo ${ip}#${local}>>${GITHUB_WORKSPACE}/addressesapi.txt
            sleep 1
          done
          rm -f ${GITHUB_WORKSPACE}/proxy.txt

      - name: Creat Message
        id: msg
        run: |
            echo "commit_message=Update $(date +"%Y-%m-%d %H:%M:%S")" >> "$GITHUB_OUTPUT"
 
      - name: Apply IP Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: ${{ steps.msg.outputs.commit_message }}
         branch: main
         commit_user_name: hubbylei
         commit_user_email: ${{ secrets.EMAIL }}
         commit_author: hubbylei <${{ secrets.EMAIL }}>

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 5
