name: "Auto Update"
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get IP
        run: |
          echo Get IP
          curl -sL https://ip.164746.xyz/ipTop10.html | awk -F "," '{for(i=1;i<=NF;i++) print $i}' > bestcf.txt

      - name: GEO
        run: |
            if [ -f addressesapi.txt ];then
                rm -f addressesapi.txt
            fi
            num=1
            for ip in $(cat bestcf.txt)
            do
                echo ${ip}#${num}>>addressesapi.txt
                num=$((${num}+1))
                sleep 2
            done
            rm  bestcf.txt

      - name: Creat Message
        id: msg
        run: |
            echo "commit_message=Update $(date +"%Y-%m-%d %H:%M:%S")" >> "$GITHUB_OUTPUT"
 
      - name: Apply IP Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: ${{ steps.msg.outputs.commit_message }}
         branch: main
         commit_user_name: hubbylei
         commit_user_email: ${{ secrets.EMAIL }}
         commit_author: hubbylei <${{ secrets.EMAIL }}>

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 5
